// ═══════════════════════════════════════════════════════════════════
//  DICCIONARIO DE LA INTERFAZ · UI DICTIONARY
//
//  Se traduce lo que EXPLICA, no lo que NOMBRA.
//
//  Fuera de este diccionario, a propósito:
//    · Nombres de etapa — Full Application, Clear to Close, CD Issued.
//      El equipo los dice en inglés porque así los dice Arive y así los
//      dicen los lenders. Traducirlos rompería la correspondencia con el
//      resto de su día de trabajo.
//    · Productos — FHA, Conventional, DSCR, Jumbo.
//    · Términos de industria — CTC, COE, CD, TRID, DPA, lock, float, bps.
//    · Nombres propios — lenders, personas, Smart Bee, APG Realty.
// ═══════════════════════════════════════════════════════════════════

export const UI = {

  // ─── acciones ───
  save:        { es:"GUARDAR",        en:"SAVE" },
  cancel:      { es:"CANCELAR",       en:"CANCEL" },
  close:       { es:"CERRAR",         en:"CLOSE" },
  advance:     { es:"AVANZAR",        en:"ADVANCE" },
  closeFile:   { es:"CERRAR ARCHIVO", en:"CLOSE FILE" },
  reopen:      { es:"REABRIR",        en:"REOPEN" },
  refer:       { es:"REFERIR",        en:"REFER" },
  prep:        { es:"PREPARACIÓN",    en:"PREP" },
  archive:     { es:"ARCHIVAR",       en:"ARCHIVE" },
  restore:     { es:"RESTAURAR",      en:"RESTORE" },
  del:         { es:"BORRAR",         en:"DELETE" },
  add:         { es:"AGREGAR",        en:"ADD" },
  search:      { es:"Buscar cliente…", en:"Search borrower…" },
  newFile:     { es:"+ ARCHIVO NUEVO", en:"+ NEW FILE" },
  help:        { es:"AYUDA",          en:"HELP" },
  training:    { es:"ENTRENAMIENTO",  en:"TRAINING" },

  // ─── puertas de etapa ───
  gateTitle:   { es:"FALTA ALGO PARA SALIR DE ESTA ETAPA", en:"SOMETHING IS MISSING TO LEAVE THIS STAGE" },
  gateSub:     { es:"Saltarse esto deja un hueco que después nadie puede llenar.",
                 en:"Skipping this leaves a hole nobody can fill later." },
  gateSoftTitle:{ es:"Puedes avanzar, pero mira esto:", en:"You can advance, but look at this:" },
  gateGotIt:   { es:"ENTENDIDO", en:"GOT IT" },
  gateAdvanceAnyway:{ es:"AVANZAR DE TODAS FORMAS", en:"ADVANCE ANYWAY" },
  gateAskAdmin:{ es:"Solo Jose puede desbloquear esto, y queda registrado con la razón.",
                 en:"Only Jose can unlock this, and it is recorded with the reason." },
  gateOverride:{ es:"DESBLOQUEAR COMO ADMIN", en:"OVERRIDE AS ADMIN" },
  gateReason:  { es:"RAZÓN DEL DESBLOQUEO", en:"REASON FOR THE OVERRIDE" },
  // El placeholder anterior era una frase completa y bien redactada, asi
  // que se leia como un campo YA LLENO. Se toca OVERRIDE, el codigo exige
  // razon escrita, no la encuentra, y parece que el boton no hace nada.
  gateReasonPh:{ es:"Escribe aquí por qué…", en:"Type why here…" },
  apprBlocked: { es:"No se puede pedir la tasación hasta que el cliente firme las disclosures. La paga él, y la Regulación Z prohíbe cobrarle antes de que reciba el LE y manifieste su intención de proceder — 12 CFR 1026.19(a)(1)(iv).",
                 en:"The appraisal cannot be ordered until the client signs the disclosures. They pay for it, and Regulation Z bars charging them before they receive the LE and indicate intent to proceed — 12 CFR 1026.19(a)(1)(iv)." },
  gateNeedReason:{ es:"Escribe la razón. Un desbloqueo sin razón no sirve de nada dentro de tres meses.",
                   en:"Write the reason. An override with no reason is worthless three months from now." },
  closeDateAsk:{ es:"¿En qué fecha fondeó de verdad? (AAAA-MM-DD)\n\nEsta fecha decide en qué corte de payroll entra — no es la fecha de cierre esperada.",
                 en:"What date did it actually fund? (YYYY-MM-DD)\n\nThis date decides which payroll cut it lands in — it is not the expected closing date." },
  closeDateBad:{ es:"Esa fecha no se entiende. Usa AAAA-MM-DD.", en:"That date is not readable. Use YYYY-MM-DD." },

  // ─── textos que estaban fijos en App.jsx ───
  // Veinticuatro cadenas escritas directo en el JSX, fuera del diccionario.
  // Las de login son las que mas dolian: quien se equivoca de contraseña el
  // primer dia recibe un mensaje que no entiende, antes de haber podido
  // tocar ningun toggle.
  errNeedBoth:  { es:"Hacen falta el correo y la contraseña.", en:"Email and password required." },
  errBadLogin:  { es:"Correo o contraseña incorrectos.", en:"Incorrect email or password." },
  errTooMany:   { es:"Demasiados intentos fallidos. Espera unos minutos o restablece tu contraseña.",
                  en:"Too many failed attempts. Try again in a few minutes or reset your password." },
  errNoNet:     { es:"Sin conexión a internet. Revisa tu red y vuelve a intentar.",
                  en:"No internet connection. Check your network and try again." },
  errSignIn:    { es:"No se pudo entrar. Vuelve a intentar.", en:"Sign in failed. Try again." },
  errNeedEmail: { es:"Escribe tu correo arriba y después toca Restablecer.",
                  en:"Enter your email above first, then click Reset." },
  errResetFail: { es:"No se pudo mandar el correo de restablecimiento. Revisa la dirección.",
                  en:"Could not send reset email. Check the email address." },
  phPassword:   { es:"Tu contraseña...", en:"Enter your password..." },

  errNotBackup: { es:"Este archivo no parece un respaldo válido del pipeline. No se encontró ningún préstamo.",
                  en:"This file does not look like a valid pipeline backup. No files found." },
  errBadJson:   { es:"No se pudo leer el respaldo. Asegúrate de que sea un JSON exportado por esta aplicación.",
                  en:"Could not read backup file. Make sure it is a valid JSON file exported from this app." },
  errAdminOnly: { es:"Solo los administradores pueden borrar archivos. Pídeselo a Jose.",
                  en:"Only admins can delete files. Ask Jose to delete this for you." },
  backupHint:   { es:"Solo administradores — restaura tu pipeline desde un respaldo JSON",
                  en:"Admin only — restore your pipeline from a JSON backup file" },

  reviewSub:    { es:"Archivos en Preparación cuya fecha de revisión ya llegó",
                  en:"Preparation files whose review date has arrived" },
  reviewHint:   { es:"Llegó la fecha de revisión. Decide: continuar, reprogramar o archivar.",
                  en:"The review date arrived. Decide: continue, reschedule, or archive." },
  prepHint:     { es:"Vivos pero todavía no compran. Sin reloj de etapa — estos esperan contra una fecha de revisión.",
                  en:"Alive but not buyable yet. No stage clock — these wait against a review date." },
  reviewEmpty:  { es:"Nada pendiente hoy. ✓", en:"Nothing due today. ✓" },
  prepEmpty:    { es:"No hay archivos en Preparación.", en:"No files in Preparation." },
  prepEmptyHow: { es:"Para mandar uno: abre cualquier archivo activo → ⏸ PREP → escoge una razón y una fecha de revisión.",
                  en:"To send one here: open any active file → ⏸ PREP → pick a reason and a review date." },

  phSearch:     { es:"Buscar cliente...", en:"Search borrower..." },
  phLegalName:  { es:"Nombre legal completo", en:"Full legal name" },
  phPartner:    { es:"Agente, contador, Smart Bee, cliente que llegó solo...",
                  en:"Agent name, CPA, Smart Bee, walk-in..." },
  phNoteSample: { es:"Esperando talones de pago actualizados", en:"Waiting on updated pay stubs" },
  inboundLabel: { es:"Este es un referido entrante", en:"This is an inbound referral" },
  inboundEmpty: { es:"Todavía no hay referidos entrantes.", en:"No inbound referrals yet." },
  inboundEmptyHow:{ es:"Para agregar uno: toca «+ NEW FILE» → marca «Este es un referido entrante» arriba.",
                    en:"To add an inbound: click «+ NEW FILE» → check «This is an inbound referral» at the top." },
  noDataBranch: { es:"Sin dato — los reportes usan el default de la sucursal.",
                  en:"No data — reports use the branch default." },
  dpaStackHint: { es:"Conventional arriba, FHA DPA abajo", en:"Conventional on top, FHA DPA below" },
  reviewedBy:   { es:"Jose revisó esto", en:"Jose reviewed this" },

  // ─── recorrido guiado ───
  // El texto de los 24 pasos vive en `tour.jsx` junto al catalogo: cada
  // paso nombra un campo, y separarlos garantizaba que uno cambiara sin
  // el otro. Aqui solo lo que la interfaz dice ALREDEDOR del recorrido.
  trainResetAsk: { es:"Empezar de nuevo borra tu archivo de entrenamiento. ¿Seguir?",
                   en:"Starting over deletes your training file. Continue?" },
  trainBadge:    { es:"ENTRENAMIENTO", en:"TRAINING" },
  trainCloseAsk: { es:"{n} es tu archivo de entrenamiento. Si lo cierras, el recorrido de las próximas semanas se acaba aquí. ¿Cerrarlo de todas formas?",
                   en:"{n} is your training file. Closing it ends the walkthrough for the coming weeks. Close it anyway?" },
  trainNote:     { es:"Este archivo no entra a producción, ni al scorecard, ni a la cola de nadie.",
                   en:"This file never enters production, the scorecard, or anyone's queue." },
  signOut:     { es:"SALIR",          en:"SIGN OUT" },
  backup:      { es:"RESPALDO",       en:"BACKUP" },

  // ─── campos del archivo ───
  borrower:    { es:"CLIENTE",             en:"BORROWER" },
  loanType:    { es:"TIPO DE PRÉSTAMO",    en:"LOAN TYPE" },
  loanAmount:  { es:"MONTO DEL PRÉSTAMO",  en:"LOAN AMOUNT" },
  loanOfficer: { es:"ORIGINADOR",          en:"LOAN OFFICER" },
  referralPartner:{ es:"SOCIO REFERIDOR",  en:"REFERRAL PARTNER" },
  phone:       { es:"TELÉFONO",            en:"PHONE" },
  email:       { es:"CORREO",              en:"EMAIL" },
  stage:       { es:"ETAPA",               en:"STAGE" },
  closingDate: { es:"FECHA DE CIERRE",     en:"CLOSING DATE" },
  actualClose: { es:"FECHA REAL DE CIERRE",en:"ACTUAL CLOSE DATE" },
  daysInStage: { es:"DÍAS EN LA ETAPA",    en:"DAYS IN STAGE" },
  notes:       { es:"NOTAS",               en:"NOTES" },
  activity:    { es:"ACTIVIDAD",           en:"ACTIVITY" },
  showAll:     { es:"VER TODO",            en:"SHOW ALL" },
  state:       { es:"ESTADO",              en:"STATE" },

  // ─── notas ───
  addUpdate:   { es:"+ AGREGAR ACTUALIZACIÓN", en:"+ ADD UPDATE" },
  notePlaceholder: { es:"Qué pasó hoy · quién lo dijo · qué sigue",
                     en:"What happened today · who said it · what's next" },
  noteFromBanker:  { es:"Actualización del banquero receptor…",
                     en:"Update from the receiving banker…" },
  noteHint:    { es:"Cada actualización queda con su fecha y su autor. La tarjeta siempre muestra la última.",
                 en:"Every update is stamped with its date and author. The card always shows the latest." },
  noteLegacy:  { es:"anterior al historial · sin fecha ni autor confiables",
                 en:"predates the log · no reliable date or author" },
  seeLast2:    { es:"▾ ver solo las 2 últimas", en:"▾ show only the last 2" },
  seeAll:      { es:"▸ ver las {n} entradas",   en:"▸ show all {n} entries" },
  tooLong:     { es:"muy larga",  en:"too long" },
  keepShort:   { es:"sé breve",   en:"keep it short" },

  // ─── vistas ───
  activePipeline:{ es:"PIPELINE ACTIVO",   en:"ACTIVE PIPELINE" },
  closedFiles: { es:"ARCHIVOS CERRADOS",   en:"CLOSED FILES" },
  referredOut: { es:"REFERIDOS AFUERA",    en:"REFERRED OUT" },
  inbound:     { es:"REFERIDOS RECIBIDOS", en:"INBOUND" },
  preparation: { es:"PREPARACIÓN",         en:"PREPARATION" },
  dueReview:   { es:"REVISIÓN PENDIENTE",  en:"DUE REVIEW" },
  archived:    { es:"ARCHIVADOS",          en:"ARCHIVED" },
  production:  { es:"PRODUCCIÓN",          en:"PRODUCTION" },

  // ─── estado y avisos ───
  saving:      { es:"guardando…",  en:"saving…" },
  saved:       { es:"guardado",    en:"saved" },
  saveError:   { es:"no se guardó",en:"not saved" },
  critical:    { es:"CRÍTICO",     en:"CRITICAL" },
  warning:     { es:"AVISO",       en:"WARNING" },
  savesWith:   { es:"se guarda con GUARDAR ↓", en:"saves with SAVE ↓" },
  noFiles:     { es:"No hay archivos aquí todavía.", en:"No files here yet." },
  confirmDelete:{ es:"¿Borrar este archivo? No se puede deshacer.",
                  en:"Delete this file? This cannot be undone." },


  // ─── bloques del archivo ───
  contingencies:{ es:"⏱ CONTINGENCIAS", en:"⏱ CONTINGENCIES" },
  contClock:   { es:"el reloj corre desde la aceptación del contrato, no desde hoy",
                 en:"the clock runs from contract acceptance, not from today" },
  fromContract:{ es:"DEL CONTRATO · el depósito está en riesgo",
                 en:"FROM THE CONTRACT · the deposit is at risk" },
  deliveryChain:{ es:"CADENA DE ENTREGA · credibilidad y per diem",
                  en:"DELIVERY CHAIN · credibility and per diem" },
  contractAccepted:{ es:"FECHA DE ACEPTACIÓN DEL CONTRATO", en:"CONTRACT ACCEPTANCE DATE" },
  appraisal:   { es:"TASACIÓN",  en:"APPRAISAL" },
  loanCont:    { es:"PRÉSTAMO",  en:"LOAN" },
  funding:     { es:"FONDEO",    en:"FUNDING" },
  resultPerCont:{ es:"RESULTADO POR CONTINGENCIA", en:"OUTCOME PER CONTINGENCY" },
  conflicts:   { es:"CONFLICTO", en:"CONFLICT" },
  conflictsPl: { es:"CONFLICTOS",en:"CONFLICTS" },
  record:      { es:"REGISTRAR", en:"RECORD" },
  derivedDates:{ es:"FECHAS TOPE DERIVADAS", en:"DERIVED DEADLINES" },
  history:     { es:"HISTORIAL", en:"HISTORY" },

  lenderLock:  { es:"◆ LENDER Y LOCK", en:"◆ LENDER & LOCK" },
  channelDecides:{ es:"el canal decide qué lenders existen",
                   en:"the channel decides which lenders exist" },
  channel:     { es:"CANAL",   en:"CHANNEL" },
  lender:      { es:"LENDER",  en:"LENDER" },
  rate:        { es:"TASA %",  en:"RATE %" },
  lockState:   { es:"ESTADO",  en:"STATUS" },
  floating:    { es:"Flotando",en:"Floating" },
  locked:      { es:"Lockeado",en:"Locked" },
  lockDate:    { es:"FECHA DEL LOCK", en:"LOCK DATE" },
  lockTerm:    { es:"TÉRMINO",       en:"TERM" },
  backupLender:{ es:"LENDER DE RESPALDO", en:"BACKUP LENDER" },
  changeLender:{ es:"⇄ CAMBIAR DE LENDER", en:"⇄ CHANGE LENDER" },
  compensation:{ es:"COMPENSACIÓN", en:"COMPENSATION" },

  fileComp:    { es:"$ COMPENSACIÓN DEL ARCHIVO", en:"$ FILE COMPENSATION" },
  yourComp:    { es:"$ TU COMPENSACIÓN EN ESTE ARCHIVO", en:"$ YOUR COMPENSATION ON THIS FILE" },
  clientOrigin:{ es:"ORIGEN DEL CLIENTE", en:"CLIENT ATTRIBUTION" },
  grossComm:   { es:"Comisión bruta",     en:"Gross commission" },
  adjustments: { es:"AJUSTES",            en:"ADJUSTMENTS" },
  otherAdj:    { es:"+ otro ajuste",      en:"+ another adjustment" },
  distribution:{ es:"DISTRIBUCIÓN",       en:"DISTRIBUTION" },
  yourCompShort:{ es:"TU COMPENSACIÓN",   en:"YOUR COMPENSATION" },
  notYourFile: { es:"Este archivo está asignado a otro originador.",
                 en:"This file is assigned to another originator." },
  loggedWithFile:{ es:"Registrados con el archivo.", en:"Logged with the file." },


  // ─── textos explicativos · los que más importan traducir ───
  savesWithSave:{ es:"se guarda con SAVE ↓", en:"saves with SAVE ↓" },
  unsaved:     { es:" · sin guardar", en:" · unsaved" },
  unassigned:  { es:"— sin asignar —", en:"— unassigned —" },
  typingYear:  { es:"escribiendo el año…", en:"typing the year…" },
  branchLending:{ es:"Del Valle Lending Co.", en:"Del Valle Lending Co." },
  branchPowered:{ es:"powered by Barrett Financial Group", en:"powered by Barrett Financial Group" },
  borrowerRequired:{ es:"El nombre del cliente es obligatorio.", en:"Borrower name is required." },
  dupWarn:{ es:"Ya hay {n} archivo(s) que parecen ser esta misma persona:",
            en:"There are already {n} file(s) that look like this same person:" },
  dupAsk:{ es:"¿Crear el archivo de todas formas?", en:"Create the file anyway?" },
  dupEmail:{ es:"mismo correo",   en:"same email" },
  dupPhone:{ es:"mismo teléfono", en:"same phone" },
  dupName:{ es:"mismo nombre",    en:"same name" },
  notesEnglishOnly:{ es:"Las notas van en inglés — regla de la sucursal",
                     en:"Notes go in English — branch rule" },
  processor:{ es:"PROCESADORA", en:"PROCESSOR" },
  processorHint:{ es:"Quién procesa este archivo. Se decide antes de registrar — al registrar, Arive asigna y ya no se cambia aquí.",
                  en:"Who processes this file. Decided before registration — once registered, Arive assigns it and this no longer changes it." },
  processorExternal:{ es:"externa · también procesa para otras sucursales",
                      en:"external · also processes for other branches" },
  processorSheet:{ es:"↓ HOJA DE {n}", en:"↓ {n}'S SHEET" },

  // ─── hallazgos ───
  findings:{ es:"⚑ HALLAZGOS", en:"⚑ FINDINGS" },
  findingsHint:{ es:"Lo que alguien vio y todavía no está resuelto. Vive con el archivo, no en un correo — quien lo abra lo ve.",
                 en:"What someone spotted and is not resolved yet. It lives with the file, not in an email — whoever opens it sees it." },
  findingOpen:{ es:"{n} abierto(s)", en:"{n} open" },
  findingNone:{ es:"Nada abierto en este archivo.", en:"Nothing open on this file." },
  findingAdd:{ es:"+ LEVANTAR HALLAZGO", en:"+ RAISE A FINDING" },
  findingItem:{ es:"PUNTO", en:"ITEM" },
  findingWhat:{ es:"QUÉ PASA", en:"WHAT IS WRONG" },
  findingWhatPlaceholder:{ es:"Hueco de 4 meses sin carta de explicación",
                           en:"4-month gap with no letter of explanation" },
  findingWaiting:{ es:"SE ESPERA", en:"WAITING ON" },
  findingSave:{ es:"GUARDAR HALLAZGO", en:"SAVE FINDING" },
  findingResolve:{ es:"RESOLVER", en:"RESOLVE" },
  findingResolved:{ es:"resuelto {d} · {who}", en:"resolved {d} · {who}" },
  findingDaysOpen:{ es:"{n}d abierto", en:"{n}d open" },
  findingTookDays:{ es:"tardó {n}d", en:"took {n}d" },
  findingHistory:{ es:"RESUELTOS", en:"RESOLVED" },
  findingNeedsText:{ es:"Escribe qué pasa — un hallazgo sin descripción no le sirve a nadie.",
                     en:"Write what is wrong — a finding with no description helps nobody." },

  // ─── registro ───
  register:{ es:"✓ REGISTRADO CON EL LENDER", en:"✓ REGISTERED WITH LENDER" },
  registerHint:{ es:"Marca la fecha de registro, avanza la etapa y el archivo pasa a la procesadora asignada.",
                 en:"Stamps the registration date, advances the stage, and hands the file to the assigned processor." },
  registerConfirm:{ es:"¿Registrado con el lender? Se marca hoy y el archivo pasa a {p}.",
                    en:"Registered with the lender? It stamps today and hands the file to {p}." },
  registeredOn:{ es:"Registrado {d}", en:"Registered {d}" },
  registeredBy:{ es:" por {who}", en:" by {who}" },
  reRegisterNeeded:{ es:"⚠ Cambió de lender — hay que registrarlo otra vez con {n}",
                     en:"⚠ Lender changed — it has to be registered again with {n}" },
  registerTimes:{ es:"registro {n} de este archivo", en:"registration {n} on this file" },

  // ─── guarda del lender ───
  registerNoLender:{ es:"ASIGNA UN LENDER PRIMERO", en:"ASSIGN A LENDER FIRST" },
  registerNoLenderHint:{ es:"Registrar es registrar CON alguien. Escoge el lender en la solapa LENDER y este botón se enciende solo.",
                         en:"Registering means registering WITH somebody. Pick the lender on the LENDER tab and this button turns on by itself." },

  // ─── números del préstamo ───
  loanNumbers:{ es:"NÚMEROS DEL PRÉSTAMO", en:"LOAN NUMBERS" },
  loanNoInvestor:{ es:"LOAN # INVESTOR", en:"INVESTOR LOAN #" },
  loanNoLender:{ es:"LOAN # LENDER", en:"LENDER LOAN #" },
  loanNoHint:{ es:"Los devuelve Arive al registrar. Viven con este registro — si cambias de lender, el nuevo trae los suyos.",
               en:"Arive returns them at registration. They live with this registration — change lender and the new one brings its own." },
  loanNoOne:{ es:"En broker suele bastar uno", en:"In broker one is usually enough" },

  // ─── divulgaciones ───
  discSent:{ es:"Divulgaciones enviadas", en:"Disclosures sent" },
  discEsigned:{ es:"Firmadas por el cliente", en:"Signed by the borrower" },
  barrettDisc:{ es:"Barrett Disclosure en Arive", en:"Barrett Disclosure in Arive" },
  discHint:{ es:"Salen el mismo día del registro. Solo la firma es un toque aparte — nadie más sabe cuándo firmó.",
             en:"They go out the same day as registration. Only the signature is a separate tap — nobody else knows when they signed." },

  // ─── relleno de archivos anteriores ───
  bfBtn:{ es:"↻ RELLENAR", en:"↻ BACKFILL" },
  bfTitle:{ es:"RELLENO DE ARCHIVOS ANTERIORES", en:"BACKFILL OF EARLIER FILES" },
  bfLead:{ es:"Estos archivos se registraron y se sometieron de verdad — nadie lo anotó, porque los botones todavía no existían. Aquí se cierran de una sentada.",
           en:"These files really were registered and submitted — nobody recorded it, because the buttons did not exist yet. Here they get closed in one sitting." },
  bfOnlyPast:{ es:"Solo se pregunta por lo que TUVO que ocurrir. Si el archivo está en CD Issued, pasó por underwriting por fuerza; si está en UW Review, la fecha de fondeo no se pregunta.",
               en:"It only asks for what MUST have happened. A file at CD Issued went through underwriting by force; a file at UW Review is not asked for a funding date." },
  bfCount:{ es:"{f} archivo(s) · {n} fecha(s) sin anotar", en:"{f} file(s) · {n} date(s) unrecorded" },
  bfNone:{ es:"No hay nada que rellenar. Todos los archivos tienen sus fechas.",
           en:"Nothing to backfill. Every file has its dates." },
  bfSave:{ es:"GUARDAR RELLENO", en:"SAVE BACKFILL" },
  bfSaved:{ es:"{n} archivo(s) actualizado(s)", en:"{n} file(s) updated" },
  bfBlank:{ es:"Lo que no sepas déjalo en blanco. Una fecha inventada es peor que una celda vacía.",
            en:"Leave blank what you do not know. An invented date is worse than an empty cell." },
  bfWasBackfilled:{ es:"rellenado {d}", en:"backfilled {d}" },

  // ─── resumen de procesamiento, del lado del LO ───
  procStatus:{ es:"⚙ ESTADO DE PROCESAMIENTO", en:"⚙ PROCESSING STATUS" },
  procReadOnly:{ es:"solo lectura", en:"read only" },
  procWhere:{ es:"Esto lo trabajan Tina y la procesadora. Se ve aquí para que nadie tenga que preguntar por correo; se toca en la pantalla de PROCESAMIENTO.",
              en:"Tina and the processor work this. It shows here so nobody has to ask by email; it is edited on the PROCESSING screen." },
  sumRegister:{ es:"REGISTRO", en:"REGISTRATION" },
  sumNone:{ es:"—", en:"—" },
  sumOf:{ es:"{a} de {b}", en:"{a} of {b}" },
  findingNotYours:{ es:"se espera {w}", en:"waiting {w}" },

  // ─── checklist en PDF ───
  chkPrint:{ es:"↓ CHECKLIST DE BARRETT", en:"↓ BARRETT CHECKLIST" },
  chkBusy:{ es:"↓ GENERANDO…", en:"↓ BUILDING…" },
  chkHint:{ es:"La forma de Barrett con lo que el sistema ya sabe. Lo que falta sale en blanco, para escribirlo a mano. Va al expediente y a payroll.",
            en:"Barrett's own form with what the system already knows. What is missing prints blank, to fill in by hand. It goes to the file and to payroll." },
  chkFailed:{ es:"No se pudo generar el PDF. Revisa la conexión e intenta de nuevo.",
              en:"Could not build the PDF. Check your connection and try again." },

  // ─── hitos ───
  milestones:{ es:"HITOS", en:"MILESTONES" },
  milestonesHint:{ es:"Fechas de la forma de Barrett que ningún avance de etapa produce. Un toque sella hoy; el segundo lo quita.",
                   en:"Dates on Barrett's form that no stage advance produces. One tap stamps today; a second one removes it." },
  milestoneNone:{ es:"pendiente", en:"pending" },

  // ─── resultado de underwriting ───
  uwResult:{ es:"RESULTADO DE UNDERWRITING", en:"UNDERWRITING OUTCOME" },
  uwResultHint:{ es:"Aprobado, suspendido o denegado no son la misma fecha. Suspendido enciende el rojo de la hoja de Martha.",
                 en:"Approved, suspended and denied are not the same date. Suspended turns on the red on Martha's sheet." },
  uwResultNone:{ es:"Sin resultado registrado todavía.", en:"No outcome recorded yet." },
  uwResultOn:{ es:"{o} el {d}", en:"{o} on {d}" },
  uwResultNote:{ es:"Qué dijo el underwriter", en:"What the underwriter said" },
  uwClear:{ es:"QUITAR", en:"CLEAR" },

  // ─── fecha prometida por el vendor ───
  orderDue:{ es:"Prometida", en:"Due" },
  orderDueHint:{ es:"La fecha que promete el vendor. Si pasa y no llegó, sale en rojo.",
                 en:"The date the vendor promises. If it passes with nothing received, it turns red." },
  orderLate:{ es:"pasó la fecha prometida", en:"past the promised date" },

  // ─── verificación de los puntos del 1003 ───
  gate1Title:{ es:"VERIFICACIÓN DEL 1003", en:"1003 VERIFICATION" },
  gate1Hint:{ es:"Un toque gira: pendiente → verificado → no aplica. Marcar que revisaste y salió bien no es un hallazgo — el rojo se reserva para lo que está roto.",
              en:"One tap cycles: pending → verified → N/A. Recording that you checked and it was clean is not a finding — red is reserved for what is broken." },
  gate1Coverage:{ es:"{d} de {t} · {p} sin revisar", en:"{d} of {t} · {p} unchecked" },
  gate1AllDone:{ es:"✓ Los {t} puntos revisados", en:"✓ All {t} items checked" },
  gate1Blocked:{ es:"Hay un hallazgo abierto en este punto — resuélvelo primero",
                 en:"There is an open finding on this item — resolve it first" },
  gate1StampedBy:{ es:"{d} · {who}", en:"{d} · {who}" },

  // ─── contrato ───
  contractSignal:{ es:"FIRMA DEL COMPRADOR", en:"CONTRACT SIGNAL DATE" },
  contractSignalHint:{ es:"Cuándo firmó el comprador. El reloj sigue corriendo desde la aceptación del vendedor — esta no mueve ninguna fecha.",
                       en:"When the buyer signed. The clock still runs from the seller's acceptance — this moves no deadline." },
  signalGap:{ es:"{n}d entre la firma y la aceptación", en:"{n}d between signing and acceptance" },

  // ─── pantalla de procesamiento ───
  processingTab:{ es:"⚙ PROCESAMIENTO", en:"⚙ PROCESSING" },
  orders:{ es:"PEDIDOS", en:"ORDERS" },
  orderReq:{ es:"Pedido", en:"Ordered" },
  orderRec:{ es:"Recibido", en:"Received" },
  orderWaiting:{ es:"{n}d esperando", en:"{n}d waiting" },
  orderUndo:{ es:"Toca otra vez para quitar el sello", en:"Tap again to remove the stamp" },
  orderUndoAsk:{ es:"¿Quitar?", en:"Remove?" },
  oneShot:{ es:"ORDENAR TODO", en:"ORDER ALL" },
  oneShotHint:{ es:"Título, HOI y tasación de un tiro, con la fecha de hoy",
                en:"Title, HOI and appraisal in one shot, stamped today" },
  ordersHint:{ es:"Un toque estampa hoy. Estas fechas son las que llenan las columnas de pedidos en la hoja de procesamiento.",
               en:"One tap stamps today. These dates fill the order columns on the processing sheet." },
  queueEmpty:{ es:"Nada en esta cola ahora mismo.", en:"Nothing in this queue right now." },
  queuePick:{ es:"Escoge un archivo de la cola.", en:"Pick a file from the queue." },
  closeInDays:{ es:"cierra en {n}d", en:"closes in {n}d" },
  stageDays:{ es:"{n}d en la etapa", en:"{n}d in stage" },
  openFullFile:{ es:"ABRIR EL ARCHIVO COMPLETO", en:"OPEN THE FULL FILE" },
  orderNoteHint:{ es:"Qué contestó el vendor", en:"What the vendor said" },
  orderNotePlaceholder:{ es:"Título dice 3 días más · el tasador necesita acceso",
                         en:"Title says 3 more days · appraiser needs access" },
  noDeadlines:{ es:"Sin fechas derivadas — falta capturar las contingencias.",
                en:"No derived deadlines — the contingencies are not captured yet." },

  // ─── admisión ───
  intake:{ es:"ADMISIÓN", en:"INTAKE" },
  intakeCoverage:{ es:"{f} de {t} capturados", en:"{f} of {t} captured" },
  intakeHint:{ es:"Los marcados con ◆ deciden qué programa de DPA aplica. Se capturan una vez y sirven para el checklist y para el DPA.",
               en:"The ones marked ◆ decide which DPA program applies. Captured once, they serve both the checklist and DPA." },
  dpaDataYes:{ es:"◆ datos completos para DPA", en:"◆ DPA data complete" },
  dpaDataNo:{ es:"◆ faltan datos para DPA", en:"◆ DPA data missing" },

  // ─── DPA por atributos ───
  dpaBlock:{ es:"◈ ASISTENCIA (DPA)", en:"◈ DOWN PAYMENT ASSISTANCE" },
  dpaPctLabel:{ es:"PORCENTAJE", en:"PERCENTAGE" },
  dpaForm:{ es:"FORMA", en:"FORM" },
  dpaYears:{ es:"AÑOS PARA EL PERDÓN", en:"YEARS TO FORGIVENESS" },
  dpaIncomplete:{ es:"falta el porcentaje o la forma", en:"missing the percentage or the form" },
  dpaBlockHint:{ es:"El producto sale del tipo de préstamo, arriba. Aquí solo va cuánto y cómo se devuelve — así el reporte cruza los dos sin que se contradigan.",
                 en:"The product comes from the loan type above. Here you only set how much and how it is repaid — so the report crosses both without contradicting itself." },
  noDpaRow:{ es:"sin DPA", en:"no DPA" },
  miWrong:{ es:"¿{n}%? El MI casi nunca pasa de un dígito — revisa si se cayó un decimal.",
            en:"{n}%? MI almost never goes above a single digit — check for a lost decimal." },
  dpWrong:{ es:"¿{n}%? Este campo es el PORCENTAJE, no los dólares. Un enganche arriba de 50% no existe aquí.",
            en:"{n}%? This field is the PERCENTAGE, not the dollars. A down payment above 50% does not exist here." },
  dpUse:{ es:"USAR {n}% · del precio y el monto", en:"USE {n}% · from price and loan amount" },
  // ─── solapas del archivo ───
  tabLoan:{ es:"PRÉSTAMO", en:"LOAN" },
  tabLender:{ es:"LENDER", en:"LENDER" },
  tabDates:{ es:"FECHAS", en:"DATES" },
  tabMoney:{ es:"DINERO", en:"MONEY" },
  tabFile:{ es:"EXPEDIENTE", en:"FILE" },
  hdProduct:{ es:"PRODUCTO", en:"PRODUCT" },
  hdAmount:{ es:"MONTO", en:"AMOUNT" },
  hdLender:{ es:"LENDER", en:"LENDER" },
  hdLo:{ es:"ORIGINADOR", en:"LOAN OFFICER" },
  hdProcessor:{ es:"PROCESADORA", en:"PROCESSOR" },
  hdStage:{ es:"ETAPA", en:"STAGE" },
  hdClosing:{ es:"CIERRE", en:"CLOSING" },
  hdCeiling:{ es:"techo {n}d", en:"ceiling {n}d" },
  hdInDays:{ es:"en {n} días", en:"in {n} days" },

  // ─── código de color ───
  sigBroken:{ es:"Vencido o roto", en:"Overdue or broken" },
  sigSoon:{ es:"Se avecina", en:"Coming up" },
  sigDone:{ es:"Hecho", en:"Done" },
  sigInfo:{ es:"Dato del sistema", en:"System data" },
  sigLegal:{ es:"Legal", en:"Legal" },
  sigIdle:{ es:"Estancado", en:"Idle" },

  // ─── ritmo del archivo ───
  langHint:{ es:"Cambia tu idioma en todo el sistema, no solo en este archivo",
             en:"Changes your language across the whole system, not just this file" },
  hdPace:{ es:"RITMO", en:"PACE" },
  paceDays:{ es:"{n}d", en:"{n}d" },
  paceAhead:{ es:"adelantado", en:"ahead" },
  paceBehind:{ es:"atrasado", en:"behind" },
  paceAheadFull:{ es:"Este archivo va {n} días adelantado", en:"This file is running {n} days ahead" },
  paceBehindFull:{ es:"Este archivo va {n} días atrasado", en:"This file is running {n} days behind" },
  paceBasis:{ es:"{s} debía empezar el {d}", en:"{s} was due to start {d}" },
  paceCould:{ es:"a este ritmo podría cerrar el {d}", en:"at this pace it could close {d}" },
  paceAddendum:{ es:"Adelantar el cierre necesita addendum firmado por comprador y vendedor. El sistema no mueve el COE.",
                 en:"Moving the closing up needs an addendum signed by buyer and seller. The system does not move the COE." },
  closingToday:{ es:"cierra hoy", en:"closing today" },
  pastDue:{ es:"pasado de fecha", en:"past due" },

  // ─── barra de acciones ───
  referBtn:{ es:"REFERIR", en:"REFER OUT" },
  prepBtn:{ es:"PREPARACIÓN", en:"PREPARATION" },
  archBtn:{ es:"ARCHIVAR", en:"ARCHIVE" },
  delBtn:{ es:"BORRAR", en:"DELETE" },
  restoreBtn:{ es:"↩ RESTAURAR", en:"↩ RESTORE" },
  reopenBtn:{ es:"REABRIR ARCHIVO", en:"REOPEN FILE" },
  continueBtn:{ es:"✓ CONTINUAR", en:"✓ CONTINUE" },
  reschedBtn:{ es:"↻ REPROGRAMAR", en:"↻ RESCHEDULE" },
  pullBack:{ es:"↩ TRAER DE VUELTA", en:"↩ PULL BACK" },
  actionAnyway:{ es:"¿Hacerlo de todas formas?", en:"Do it anyway?" },
  closeAsk:{ es:"¿Cerrar el archivo de {n}?", en:"Close {n}'s file?" },
  referAsk:{ es:"¿Referir a {n} a otro banco? El archivo pasa a REFERIDO AFUERA y después llenas los datos del banquero.",
             en:"Refer {n} to another bank? The file moves to REFERRED OUT and you fill in the banker's details next." },
  pullBackAsk:{ es:"¿Traer a {n} de vuelta al pipeline? La etapa vuelve a Lead Inquiry y se borran los datos del banquero.",
                en:"Bring {n} back into the pipeline? The stage resets to Lead Inquiry and the banker data is cleared." },
  deleteAsk:{ es:"¿Borrar permanentemente? Esto no se puede deshacer.", en:"Delete permanently? This cannot be undone." },
  deleteHint:{ es:"Solo admin — borra el archivo para siempre", en:"Admin only — deletes the file permanently" },
  legacyType:{ es:"— tipo anterior, ya no se usa —", en:"— legacy type, no longer used —" },
  legacyTypeHint:{ es:"Este tipo viene del catálogo anterior y ya no se usa. Escoge el producto real y describe la asistencia en el bloque de DPA.",
                   en:"This type comes from the previous catalog and is no longer used. Pick the real product and describe the assistance in the DPA block." },
  byDpaMix:{ es:"POR DPA · qué se vende más", en:"BY DPA · what sells most" },
  byState:{ es:"POR ESTADO", en:"BY STATE" },
  noDpaYet:{ es:"Todavía no hay archivos con asistencia capturada.", en:"No files with assistance captured yet." },
  hForm:{ es:"FORMA", en:"FORM" },
  hPct:{ es:"%", en:"%" },
  hDays:{ es:"DÍAS", en:"DAYS" },
  intakeHintLo:{ es:"El LO los sabe al precalificar. Los marcados con ◆ deciden qué programa de DPA aplica — la elección del programa es del LO, no de procesamiento.",
                 en:"The LO knows these at pre-qual. The ones marked ◆ decide which DPA program applies — picking the program is the LO's call, not processing's." },

  // contingencias
  anchorHint:  { es:"Todo se cuenta desde aquí. Si el archivo pasó días en Under Contract, ya se gastaron.",
                 en:"Everything counts from here. Days the file spent in Under Contract are already spent." },
  calendarDays:{ es:"{s} cuenta días de calendario en el contrato",
                 en:"{s} counts calendar days in the contract" },
  businessDays:{ es:"FL cuenta DÍAS HÁBILES en el contrato — la misma contingencia da otra fecha",
                 en:"FL counts BUSINESS DAYS in the contract — the same contingency lands on a different date" },
  cdReceivedBy:{ es:"CD debe estar RECIBIDO el {d} — 3 días hábiles antes del cierre, por ley.",
                 en:"The CD must be RECEIVED by {d} — 3 business days before closing, by law." },
  cdCounts:    { es:"Cuenta sábados y salta domingos y feriados federales. Si se manda por correo, sale el {d}.",
                 en:"Saturdays count; Sundays and federal holidays do not. If mailed, it goes out {d}." },
  contractDaysOf:{ es:"días {b} del contrato", en:"{b} days from contract" },
  calShort:    { es:"cal.",     en:"cal." },
  bizShort:    { es:"hábiles",  en:"business" },
  depositExposed:{ es:"Venció sin registrar resultado. El depósito está expuesto.",
                   en:"It passed with no outcome recorded. The deposit is exposed." },
  newDateAddendum:{ es:"Fecha nueva — requiere addendum firmado",
                    en:"New date — requires a signed addendum" },
  outcomeNote: { es:"Nota — qué pasó, quién lo confirmó",
                 en:"Note — what happened, who confirmed it" },
  derivedHint: { es:"Calculadas hacia atrás desde cada contingencia, con el techo de cada etapa — el peor caso, no el promedio.",
                 en:"Derived backward from each contingency using each stage's ceiling — worst case, not average." },

  // lender y lock
  lastDayToLock:{ es:"Último día para lockear: {d}", en:"Last day to lock: {d}" },
  daysLeftN:   { es:"faltan {n}d",  en:"{n}d left" },
  daysLateN:   { es:"{n}d tarde",   en:"{n}d late" },
  cdCarriesRate:{ es:"El CD lleva la tasa final, así que no se puede flotar más allá de su fecha legal.",
                  en:"The CD carries the final rate, so you cannot float past its legal date." },
  noCloseNoCap:{ es:"Sin fecha de cierre no hay tope calculable. Captura el COE primero.",
                 en:"Without a closing date there is no deadline to derive. Capture the COE first." },
  whichTermQ:  { es:"SI LOCKEAS HOY, ¿QUÉ TÉRMINO LLEGA AL CIERRE?",
                 en:"IF YOU LOCK TODAY, WHICH TERM REACHES CLOSING?" },
  coversBy:    { es:"cubre · +{n}d",   en:"covers · +{n}d" },
  shortByN:    { es:"corto por {n}d",  en:"short by {n}d" },
  priceDecides:{ es:"El precio decide el término, pero un lock que vence antes del cierre devuelve lo ganado en la extensión.",
                 en:"Price decides the term, but a lock that expires before closing gives the savings back in the extension." },
  expiresOn:   { es:"Vence {d}",  en:"Expires {d}" },
  coversClose: { es:" · cubre el cierre con {n}d de sobra", en:" · covers closing with {n}d to spare" },
  shortOfClose:{ es:" · {n}d antes del cierre, habrá extensión", en:" · {n}d before closing, an extension is coming" },
  lenderName:  { es:"nombre del lender", en:"lender name" },
  otherLenderHint:{ es:"Sin datos de plan ni de guías. Escribe la comp a mano y avísame para agregarlo al catálogo.",
                    en:"No plan or guideline data. Enter the comp by hand and let me know to add it to the catalog." },
  hiddenByChannel:{ es:"{n} lender(es) hace(n) este producto pero no opera(n) en correspondent, así que no aparece(n): {list}",
                    en:"{n} lender(s) do this product but do not operate in correspondent, so they are hidden: {list}" },
  andNMore:    { es:" y {n} más", en:" and {n} more" },
  makesProduct:{ es:"hacen {p}",  en:"do {p}" },

  // respaldo y cambio de lender
  safeUntil:   { es:"Seguro hasta el {d} · faltan {n}d", en:"Safe until {d} · {n}d left" },
  onlyIfNothingFails:{ es:"solo llega si todo sale bien · imposible después del {d}",
                       en:"only makes it if all goes well · impossible after {d}" },
  noLongerMakesIt:{ es:"Ya no llega · la fecha tope era el {d}", en:"No longer makes it · the deadline was {d}" },
  untilArrivesAnyway:{ es:"hasta {d} · llega aunque todo se atrase ({n}d)",
                       en:"until {d} · makes it even if everything drags ({n}d)" },
  betweenOnlyIfClean:{ es:"{a} a {b} · solo si nada falla ({n}d)",
                       en:"{a} to {b} · only if nothing fails ({n}d)" },
  afterNoMakes:{ es:"después del {d} · no llega", en:"after {d} · does not make it" },
  countedBackFromCd:{ es:"Contado hacia atrás desde el CD del {d}.", en:"Counted backward from the CD on {d}." },
  cushionBefore:{ es:"El colchón vence {n} días ANTES que la contingencia de préstamo ({d}). Dentro de la contingencia parecerá que hay tiempo y no lo habrá.",
                  en:"The cushion expires {n} days BEFORE the loan contingency ({d}). Inside the contingency it will look like there is time, and there will not be." },
  movingCosts: { es:"moverlo cuesta {b} bps · −${d}", en:"moving costs {b} bps · −${d}" },
  movingFree:  { es:"moverlo no cuesta comp · {name} llega a {n} bps",
                 en:"moving costs no comp · {name} reaches {n} bps" },
  youChargeCap:{ es:"cobras {a} · techo allá {b}", en:"you charge {a} · ceiling there {b}" },
  changeLenderTitle:{ es:"Cambiar de lender", en:"Change lender" },
  whatItCosts: { es:"LO QUE CUESTA", en:"WHAT IT COSTS" },
  newLender:   { es:"NUEVO LENDER", en:"NEW LENDER" },
  reason:      { es:"MOTIVO", en:"REASON" },
  note:        { es:"NOTA", en:"NOTE" },
  reasonNote:  { es:"qué dijo el lender, quién lo confirmó", en:"what the lender said, who confirmed it" },
  landsAt:     { es:"Aterriza en", en:"Lands at" },
  reunderwrite:{ es:"Re-suscripción", en:"Re-underwriting" },
  daysN:       { es:"{n} días", en:"{n} days" },
  travelsHint: { es:"Tasación, título, HOI y documentos viajan. Las divulgaciones son nuevas y el lender nuevo suscribe desde cero.",
                 en:"Appraisal, title, HOI and documents travel. Disclosures are new and the new lender underwrites from scratch." },
  lockNotTransfer:{ es:"El lock no se transfiere. Sueltas {r}% y vuelves a lockear al mercado del día. Si la tasa subió, la paga el cliente.",
                    en:"The lock does not transfer. You release {r}% and re-lock at that day's market. If rates rose, the borrower pays." },
  tooLateToMove:{ es:"En el peor caso este cambio ya no llega al cierre del {coe}. La fecha tope para decidir era el {d}.",
                  en:"At worst case this change no longer reaches the {coe} closing. The deadline to decide was {d}." },
  countsAgainstLender:{ es:" · cuenta contra este lender en el scorecard",
                        en:" · counts against this lender on the scorecard" },
  daysWithPrev:{ es:" · {n}d con el anterior", en:" · {n}d with the previous one" },
  moveTo:      { es:"MOVER A", en:"MOVE TO" },

  // compensación
  reportedByDash:{ es:"· lo que reportan los dashboards", en:"· what the dashboards report" },
  bpsFieldHint:{ es:"Este es el número que usan todos los reportes. El bloque de COMPENSACIÓN de abajo lo llena solo al guardar; aquí lo puedes ajustar a mano. En blanco = {n} bps.",
                 en:"This is the number every report uses. The COMPENSATION block below fills it on save; here you can adjust it by hand. Blank = {n} bps." },
  willWriteBps:{ es:"Al guardar, {n} bps pasan a BPS COMP arriba y eso es lo que reportan los dashboards.",
                 en:"On save, {n} bps go to BPS COMP above and that is what the dashboards report." },
  noCompData:  { es:"Sin dato — los reportes usan el default de la sucursal.",
                 en:"No figure — reports use the branch default." },
  combinedCap: { es:"Los 400 son combinados. Si subes uno, el otro se ajusta a lo que quede.",
                 en:"The 400 is combined. If you raise one, the other adjusts to what is left." },
  unnamedAdj:  { es:"Hay un ajuste sin nombre — no se va a guardar hasta que lo escribas.",
                 en:"There is an unnamed adjustment — it will not save until you name it." },
  adjName:     { es:"nombre del descuento", en:"deduction name" },
  creditName:  { es:"nombre del crédito",   en:"credit name" },
  toCredit:    { es:"descuento — clic para crédito", en:"deduction — click for credit" },
  toFee:       { es:"crédito — clic para descuento", en:"credit — click for deduction" },
  adjTotals:   { es:"Ajustes −${d}", en:"Adjustments −${d}" },
  credTotals:  { es:"Créditos +${d}", en:"Credits +${d}" },
  pctOfNet:    { es:"{p}% del NET de ${d}", en:"{p}% of the ${d} NET" },
  leadPending: { es:"Clasificación pendiente. Se calcula como producción propia hasta que se defina.",
                 en:"Classification pending. Counted as own production until it is defined." },
  inHouseLess: { es:"Lead de la sucursal · {n} puntos menos que producción propia",
                 en:"Branch lead · {n} points less than own production" },
  planCeiling: { es:"Pagado por el lender · tope del plan {n} bps",
                 en:"Lender-paid · plan caps at {n} bps" },
  ceilingLeft: { es:"techo {n} bps", en:"ceiling {n} bps" },
  ceilingLeftN:{ es:"techo {n} bps · quedan {r}", en:"ceiling {n} bps · {r} left" },

  cap:{ es:"tope", en:"cap" },
  guidelines:{ es:"guías ↗", en:"guidelines ↗" },


  // ─── payroll y producción ───
  year:        { es:"AÑO",  en:"YEAR" },
  filesPerMo:  { es:"ARCHIVOS/MES", en:"FILES/MO" },
  costPerFile: { es:"costo/archivo", en:"cost/file" },
  seniorCap:   { es:"techo Senior", en:"Senior cap" },
  since:       { es:"desde", en:"since" },
  currentCut:  { es:"CORTE ACTUAL", en:"CURRENT CUT" },
  barrettCloses:{ es:"Barrett cierra el 1 y el 15", en:"Barrett closes on the 1st and the 15th" },
  unclaimed:   { es:"SIN RECLAMAR", en:"UNCLAIMED" },
  fundedFiles: { es:"archivos fondeados", en:"funded files" },
  yourShare:   { es:"TE TOCA", en:"YOUR SHARE" },
  yourSplitPlusBranch:{ es:"tu split + retención de sucursal", en:"your split + branch retention" },
  fromOldCuts: { es:"DE CORTES VIEJOS", en:"FROM OLD CUTS" },
  carried:     { es:"arrastrado", en:"carried over" },
  carriedN:    { es:"{n} arrastrado(s)", en:"{n} carried over" },
  nextRequest: { es:"PARA EL PRÓXIMO REQUEST DE PAYROLL", en:"FOR THE NEXT PAYROLL REQUEST" },
  claimOptional:{ es:"reclamar es opcional · lo que no metas queda para el corte siguiente",
                  en:"claiming is optional · what you leave out stays for the next cut" },
  generateRequest:{ es:"GENERAR REQUEST", en:"GENERATE REQUEST" },
  noUnclaimed: { es:"No hay archivos fondeados sin reclamar.", en:"No funded files left unclaimed." },
  client:      { es:"CLIENTE", en:"BORROWER" },
  fundedOn:    { es:"FONDEÓ", en:"FUNDED" },
  cut:         { es:"CORTE", en:"CUT" },
  split:       { es:"SPLIT", en:"SPLIT" },
  claim:       { es:"RECLAMAR", en:"CLAIM" },
  totalFiles:  { es:"TOTAL · {n} archivos", en:"TOTAL · {n} files" },
  yourLoSplit: { es:"tu split de LO", en:"your LO split" },
  referralFeeOf:{ es:"fee de referido · {b} bps", en:"referral fee · {b} bps" },
  ofTheLo:     { es:"del LO", en:"the LO's" },
  branchPctOf: { es:"sucursal {n}%", en:"branch {n}%" },
  referredShort:{ es:"referido", en:"referred out" },
  noCompRule:  { es:"sin regla de comp", en:"no comp rule" },
  noCompRuleFor:{ es:"Sin regla de compensación: {names}. Sus archivos se reparten por volumen derivado, que puede no ser su acuerdo real.",
                  en:"No compensation rule for: {names}. Their files split by derived volume, which may not be their actual agreement." },
  payrollRequest:{ es:"Request de payroll", en:"Payroll request" },
  filesTotal:  { es:"{n} archivo(s) · total ${d}", en:"{n} file(s) · total ${d}" },
  copyText:    { es:"COPIAR TEXTO", en:"COPY TEXT" },
  copied:      { es:"COPIADO", en:"COPIED" },
  alreadySent: { es:"YA LO ENVIÉ · CERRAR CORTE", en:"ALREADY SENT · CLOSE CUT" },
  sendYourself:{ es:"Este botón no manda nada: copia el texto y pégalo en tu correo a payroll. Después ciérralo aquí para sacarlos de la lista del próximo corte y guardar la copia.",
                 en:"This button sends nothing: copy the text and paste it into your email to payroll. Then close it here to remove them from the next cut's list and keep the copy." },
  couldNotClose:{ es:"No se pudo cerrar el corte: {e}. Nada se marcó — copia el texto y avísame.",
                  en:"Could not close the cut: {e}. Nothing was marked — copy the text and let me know." },
  sentRequests:{ es:"REQUESTS ENVIADOS", en:"SENT REQUESTS" },
  inTotal:     { es:"{n} · ${d} en total", en:"{n} · ${d} in total" },
  sentBy:      { es:"enviado {d} por {who}", en:"sent {d} by {who}" },
  nFiles:      { es:"{n} archivos", en:"{n} files" },
  view:        { es:"VER", en:"VIEW" },
  copyAgain:   { es:"COPIAR DE NUEVO", en:"COPY AGAIN" },
  exactCopy:   { es:"Copia exacta de lo que se envió. No cambia aunque después se edite un archivo.",
                 en:"Exact copy of what was sent. It does not change even if a file is edited later." },
  deleteLogEntry:{ es:"¿Borrar esta entrada del historial? Los archivos no cambian.",
                   en:"Delete this history entry? The files do not change." },
  netSplitYear:{ es:"REPARTO DEL NET · año {y} · {n} archivos/mes",
                 en:"NET SPLIT · year {y} · {n} files/mo" },
  marginPerFile:{ es:"margen sucursal ${d}/archivo", en:"branch margin ${d}/file" },
  yourIncomePerFile:{ es:"tu ingreso ${d}/archivo", en:"your income ${d}/file" },
  branchKeeps:{ es:"sucursal {n}%", en:"branch {n}%" },
  youKeep:    { es:"tú {n}%", en:"you {n}%" },
  newbieNoLadder:{ es:"El Newbie no sube con la escalera — sube al graduar a Intermediate con ${m}M de volumen fondeado. Un piso contractual (⚑) nunca se suma a los aumentos de la escalera.",
                   en:"Newbies do not rise with the ladder — they rise on advancing to Intermediate at ${m}M funded. A contractual floor (⚑) never stacks on ladder increases." },
  claimedFor:  { es:"Reclamado para el corte {p} — {what}", en:"Claimed for the {p} cut — {what}" },
  filesCutTotal:{ es:"{n} archivos · ${d} · corte {p}", en:"{n} files · ${d} · {p} cut" },
  idsBackfilledMsg:{ es:"{n} archivo(s) no tenía(n) identificador y no se podía(n) editar en masa. Ya tiene(n) uno. Guarda cualquier cambio para dejarlo fijo.",
                     en:"{n} file(s) had no identifier and could not be bulk-edited. They have one now. Save any change to make it permanent." },
  migrated:{ es:"✓ {n} archivos migrados a un documento por préstamo. El pipeline anterior queda intacto como respaldo.",
             en:"✓ {n} files migrated to one document per loan. The previous pipeline stays intact as a backup." },
  docTooBig:   { es:"Un archivo pesa {mb} MB y Firestore no acepta documentos de más de 1 MB. Ese archivo NO se está guardando — casi siempre son notas de más.",
                 en:"One file weighs {mb} MB and Firestore does not accept documents over 1 MB. That file is NOT being saved — it is almost always too many notes." },
  docNearLimit:{ es:"Un archivo pesa {mb} MB. El tope de Firestore es 1 MB POR ARCHIVO — revisa si tiene notas de más.",
                 en:"One file weighs {mb} MB. Firestore's cap is 1 MB PER FILE — check whether it has too many notes." },
  // pasos del cierre de corte
  stepPrepare: { es:"preparar", en:"prepare" },
  notAFunction:{ es:"no es una función", en:"is not a function" },
  cdIssueTitle:{ es:"Último día para emitir el CD — 3 días hábiles antes del cierre, por ley",
                 en:"Last day to issue the CD — 3 business days before closing, by law" },
  stepRows:    { es:"leer las filas", en:"reading the rows" },
  stepPayees:  { es:"leer los beneficiarios", en:"reading the payees" },
  stepDate:    { es:"fechar el request", en:"dating the request" },
  stepClose:   { es:"cerrar el corte", en:"closing the cut" },
  errNoClose:  { es:"la pantalla no puede cerrar cortes", en:"the screen cannot close cuts" },
  errNoIds:    { es:"{n} archivo(s) sin identificador — refresca la página y vuelve a intentarlo",
                 en:"{n} file(s) with no identifier — refresh the page and try again" },
  errNoneFound:{ es:"no se encontró ninguno de los archivos seleccionados",
                 en:"none of the selected files were found" },
  errClipboard:{ es:"el navegador bloqueó el portapapeles", en:"the browser blocked the clipboard" },

  // ─── scorecard de lenders ───
  scorecardTab:{ es:"◆ SCORECARD DE LENDERS", en:"◆ LENDER SCORECARD" },
  scorecardLead:{ es:"El volumen colocado no dice con quién trabajar. Lo que mide a un lender es qué proporción de lo que toca termina cerrando, y cuántos archivos devuelve por decisión suya.",
                  en:"Placed volume does not tell you who to work with. What measures a lender is how much of what it touches ends up closing, and how many files it sends back on its own call." },
  scHeadLender:{ es:"LENDER", en:"LENDER" },
  scHeadTouched:{ es:"TOCA", en:"TOUCHED" },
  scHeadFunded:{ es:"CIERRA", en:"CLOSED" },
  scHeadPull: { es:"PULL-THROUGH", en:"PULL-THROUGH" },
  scHeadExits:{ es:"SALIDAS", en:"EXITS" },
  scHeadFault:{ es:"POR SU CULPA", en:"ITS OWN CALL" },
  scHeadDays: { es:"DÍAS A CIERRE", en:"DAYS TO CLOSE" },
  scHeadBps:  { es:"BPS PROM", en:"AVG BPS" },
  scHeadVerdict:{ es:"VEREDICTO", en:"VERDICT" },
  scNoData:   { es:"Todavía no hay suficientes cambios de lender registrados para medir a nadie.",
                en:"Not enough lender changes recorded yet to measure anyone." },
  scFaultNote:{ es:"Solo las salidas por decisión del lender lo miden a él. Las del cliente o de la propiedad se habrían ido con cualquiera.",
                en:"Only exits on the lender's own call measure the lender. Borrower or property exits would have happened anywhere." },
  scCompLost: { es:"comp perdida por salidas de su culpa", en:"comp lost to its own exits" },
  scMinFiles: { es:"con al menos {n} archivo(s)", en:"with at least {n} file(s)" },

  byLender:   { es:"POR LENDER", en:"BY LENDER" },
  byProduct:  { es:"POR PRODUCTO", en:"BY PRODUCT" },
  productQ:   { es:"Si tengo un {p}, ¿a quién?", en:"If I have a {p}, who gets it?" },
  proven:     { es:"PROBADOS · tienes historial con ellos", en:"PROVEN · you have history with them" },
  untried:    { es:"SIN PROBAR · lo ofrecen, nunca has cerrado ahí", en:"UNTRIED · they offer it, you have never closed there" },
  offersNotProof:{ es:"Que un lender ofrezca un producto no es evidencia de nada. Estos salen del catálogo, ordenados por lo que pagan.",
                   en:"A lender offering a product is evidence of nothing. These come from the catalog, sorted by what they pay." },
  noProductData:{ es:"Todavía no has trabajado ningún archivo con lender asignado desde el corte.",
                  en:"No files with an assigned lender since the cutover yet." },
  closedOf:   { es:"{a} de {b}", en:"{a} of {b}" },
  ownCall:    { es:"culpa suya: {n}", en:"its own call: {n}" },
  productStrength:{ es:"Un promedio general esconde lo que importa: un lender puede cerrar todo lo que le mandas en FHA y devolverte la mitad de los DSCR.",
                    en:"An overall average hides what matters: a lender can close everything you send in FHA and return half your DSCRs." },

  byDpa:      { es:"POR PROGRAMA DPA", en:"BY DPA PROGRAM" },
  dpaQ:       { es:"¿Quién hace {p}?", en:"Who does {p}?" },
  dpaLead:    { es:"El catálogo guarda, por lender, qué programas de asistencia maneja. Con DPA en la mitad de tu producción, esta es la lista corta que importa.",
                en:"The catalog records, per lender, which assistance programs they handle. With DPA at half your production, this is the short list that matters." },
  dpaLenderCount:{ es:"{n} lenders", en:"{n} lenders" },
  dpaPrograms:{ es:"{n} programas", en:"{n} programs" },
  dpaThin:    { es:"Pocos lenders manejan este programa — si es parte de tu mezcla, dependes de una lista corta.",
                en:"Few lenders handle this program — if it is part of your mix, you depend on a short list." },
  notLicensed:{ es:"CalHFA es de California. Con licencia en NV, FL y TX, esta columna no aplica a tu operación.",
                en:"CalHFA is California-only. Licensed in NV, FL and TX, this column does not apply to your operation." },

  bySpecialty:{ es:"POR ESPECIALIDAD", en:"BY SPECIALTY" },
  specQ:      { es:"¿Quién hace {p}?", en:"Who does {p}?" },
  specLead:   { es:"88 especialidades leídas directo del catálogo, ordenadas de más escasa a más común. Lo escaso es lo que limita tus opciones.",
                en:"88 specialties read straight from the catalog, sorted from scarcest to most common. Scarcity is what limits your options." },
  specThin:   { es:"Pocos lenders manejan esta especialidad. Si es parte de tu mezcla, conviene tener un segundo nombre probado antes de necesitarlo.",
                en:"Few lenders handle this specialty. If it is part of your mix, get a second proven name before you need it." },
  alsoDoes:   { es:"también", en:"also" },
  dpaDetailTitle:{ es:"DETALLE DEL PROGRAMA", en:"PROGRAM DETAIL" },
  dpaDetailHint:{ es:"Barrett no publica esto. Se captura de la guía del lender y se guarda aparte del catálogo, para que no se pierda al actualizarlo.",
                  en:"Barrett does not publish this. It is captured from the lender's guidelines and stored apart from the catalog, so it survives updates." },
  dpaPct:     { es:"ASISTENCIA %", en:"ASSISTANCE %" },
  dpaPctOf:   { es:"SOBRE", en:"OF" },
  dpaStructure:{ es:"ESTRUCTURA", en:"STRUCTURE" },
  dpaForgive: { es:"PERDÓN A (MESES)", en:"FORGIVEN AT (MONTHS)" },
  dpaFixesRate:{ es:"¿Fija la tasa?", en:"Fixes the rate?" },
  dpaMinFico: { es:"FICO MÍN", en:"MIN FICO" },
  dpaMaxDti:  { es:"DTI MÁX", en:"MAX DTI" },
  dpaStates:  { es:"ESTADOS", en:"STATES" },
  dpaNote:    { es:"Nota — límites, overlays, lo que haya que recordar", en:"Note — limits, overlays, anything worth remembering" },
  dpaEdit:    { es:"✎ EDITAR", en:"✎ EDIT" },
  dpaSave:    { es:"GUARDAR DETALLE", en:"SAVE DETAIL" },
  dpaEmpty:   { es:"+ AGREGAR DETALLE", en:"+ ADD DETAIL" },
  dpaFillHere:{ es:"Aquí capturas el detalle que Barrett no publica: porcentaje, si se perdona, grant o segunda, y si fija la tasa. Toca + AGREGAR DETALLE en cualquier lender.",
                en:"Here you capture what Barrett does not publish: percentage, forgivable or not, grant or second, and whether it fixes the rate. Tap + ADD DETAIL on any lender." },
  dpaCoverage:{ es:"{f} de {t} programas capturados · {p}%", en:"{f} of {t} programs captured · {p}%" },
  marthaBtn:{ es:"↓ HOJA MARTHA", en:"↓ MARTHA SHEET" },
  marthaBusy:{ es:"↓ GENERANDO…", en:"↓ BUILDING…" },
  marthaHint:{ es:"Genera el Excel de Martha con las columnas que el pipeline ya sabe. Solo archivos registrados.",
               en:"Builds Martha's Excel with the columns the pipeline already knows. Registered files only." },
  marthaEmpty:{ es:"No hay archivos registrados todavía. La hoja sale vacía.",
                en:"No registered files yet. The sheet would come out empty." },
  marthaFailed:{ es:"No se pudo generar el Excel. Revisa la conexión e intenta de nuevo.",
                 en:"Could not build the Excel. Check your connection and try again." },
  purchase:   { es:"precio de compra", en:"purchase price" },
  loanAmt:    { es:"monto del préstamo", en:"loan amount" },
  downPay:    { es:"enganche", en:"down payment" },
  yesShort:   { es:"Sí", en:"Yes" },
  noShort:    { es:"No", en:"No" },

  scHeadShare:{ es:"TU VOLUMEN", en:"YOUR VOLUME" },
  concentrated:{ es:"Concentración alta — un solo lender con demasiado peso es riesgo, no eficiencia.",
                 en:"High concentration — a single lender carrying too much is risk, not efficiency." },
  autoDerived:{ es:"Esta tabla se arma sola con los archivos del equipo. Nadie la mantiene a mano: al escoger lender en un archivo, ya cuenta aquí.",
                en:"This table builds itself from the team's files. Nobody maintains it by hand: choosing a lender on a file already counts here." },
  capturedBy: { es:"capturado por {who} el {d}", en:"captured by {who} on {d}" },
  anyoneCanFill:{ es:"Cualquiera del equipo puede capturar el detalle de un programa. Queda registrado quién lo escribió y cuándo, para poder corregirlo.",
                  en:"Anyone on the team can capture a program's detail. Who wrote it and when is recorded, so it can be corrected." },

  nMore:      { es:"{n} más", en:"{n} more" },
  cappedThere:{ es:"El techo de {name} es {n}, así que ahí cobrarías {a}.",
                en:"{name}'s ceiling is {n}, so there you would charge {a}." },
  notCappedThere:{ es:"El techo de {name} es {n}, así que puedes seguir cobrando lo mismo.",
                   en:"{name}'s ceiling is {n}, so you can keep charging the same." },
  youChargeToday:{ es:"Hoy cobras {n} bps.", en:"Today you charge {n} bps." },
  guideTitle: { es:"GUÍA DEL PIPELINE", en:"PIPELINE GUIDE" },
  searchGuide:{ es:"Buscar en la guía…", en:"Search the guide…" },
  noGuideMatch:{ es:"Nada coincide con esa búsqueda todavía.", en:"Nothing matches that search yet." },
  guideLive:  { es:"Los porcentajes y umbrales de esta guía los lee del sistema, no están escritos a mano. Si cambian, la guía cambia.",
                en:"The percentages and thresholds here are read from the system, not typed by hand. If they change, the guide changes." },
  result:     { es:"resultado", en:"result" },
  hide:       { es:"OCULTAR", en:"HIDE" },

  specDetailTitle:{ es:"DETALLE Y OVERLAYS", en:"DETAIL & OVERLAYS" },
  specDetailHint:{ es:"Aquí se captura lo que Barrett no publica: mínimos, overlays y cómo responde el lender de verdad. Cualquiera del equipo puede escribir; queda con su fecha y su autor.",
                   en:"Here you capture what Barrett does not publish: minimums, overlays and how the lender actually responds. Anyone on the team can write; it is stamped with date and author." },
  specFillHere:{ es:"Toca AGREGAR DETALLE en cualquier lender para capturar sus mínimos y lo que aprendas de sus overlays.",
                 en:"Tap ADD DETAIL on any lender to capture its minimums and what you learn about its overlays." },
  maxLtv:     { es:"LTV MÁX", en:"MAX LTV" },
  reserves:   { es:"RESERVAS (MESES)", en:"RESERVES (MONTHS)" },
  addObservation:{ es:"Observación nueva — overlay, condición, cómo respondieron",
                   en:"New observation — overlay, condition, how they responded" },
  observations:{ es:"OBSERVACIONES", en:"OBSERVATIONS" },
  noObservations:{ es:"Todavía nadie ha escrito nada de este lender en esta especialidad.",
                   en:"Nobody has written anything about this lender on this specialty yet." },
  specCoverage:{ es:"{f} de {t} capturados", en:"{f} of {t} captured" },

  mixTab:     { es:"◫ MEZCLA", en:"◫ MIX" },
  mixLead:    { es:"Un préstamo pertenece a dos dimensiones a la vez: un NV HIP FHA es DPA y es FHA. Las dos se cuentan por separado y ambas suman el total.",
                en:"A loan belongs to two dimensions at once: an NV HIP FHA is DPA and is FHA. Both are counted separately and both add to the total." },
  byBaseProduct:{ es:"POR PRODUCTO", en:"BY PRODUCT" },
  byGroup:    { es:"POR PROGRAMA · contra tu plan", en:"BY PROGRAM · against your plan" },
  byOriginator:{ es:"POR ORIGINADOR", en:"BY ORIGINATOR" },
  hClosed:    { es:"CERRADOS", en:"CLOSED" },
  hVolume:    { es:"VOLUMEN", en:"VOLUME" },
  hShare:     { es:"% UNID", en:"% UNITS" },
  hComp:      { es:"COMP", en:"COMP" },
  hActive:    { es:"EN CURSO", en:"IN FLIGHT" },
  hAvg:       { es:"PROMEDIO", en:"AVERAGE" },
  hPlan:      { es:"% PLAN", en:"% PLAN" },
  hDelta:     { es:"DIFERENCIA", en:"DIFFERENCE" },
  planEdit:   { es:"escribe tu % en la columna % PLAN", en:"type your % in the % PLAN column" },
  mixNoData:  { es:"Todavía no hay archivos fondeados desde el corte.", en:"No files funded since the cutover yet." },
  mixTotal:   { es:"TOTAL · {n} cerrados", en:"TOTAL · {n} closed" },
  aheadOfPlan:{ es:"por encima del plan", en:"ahead of plan" },
  behindPlan: { es:"por debajo del plan", en:"behind plan" },

  thinMix:    { es:"Con {n} archivo(s) cerrado(s) los porcentajes no dicen nada todavía. Empiezan a significar algo cerca de veinte.",
                en:"With {n} closed file(s) the percentages mean nothing yet. They start to matter around twenty." },
  noProduction:{ es:"sin producción cerrada", en:"no closed production" },

  unifies:    { es:"unifica:", en:"merges:" },
  partnerPlaceholder:{ es:"Agente, CPA, Smart Bee, walk-in…", en:"Agent, CPA, Smart Bee, walk-in…" },
  newPartner: { es:"Socio nuevo — si ya existe, escógelo de la lista para no duplicarlo.",
                en:"New partner — if it already exists, pick it from the list so it is not duplicated." },

  baseLoan:   { es:"Monto base", en:"Base loan" },
  compBasis:  { es:"Base de la comisión", en:"Comp basis" },
  financedHint:{ es:"El cargo se financia dentro del préstamo, así que el pagaré es mayor que el monto base. La comisión se paga sobre el total — igual que Arive. Déjalo en blanco o en 0 si el cliente lo paga en efectivo.",
                 en:"The fee is financed into the loan, so the note is larger than the base amount. Comp is paid on the total — same as Arive. Leave it blank or set 0 if the borrower pays it in cash." },

  compliance: { es:"✓ REQUISITOS PARA COBRAR", en:"✓ PAYROLL REQUIREMENTS" },
  complianceHint:{ es:"Barrett paga cuando el préstamo fondeó, llegó el cheque y estos documentos están en Arive. Sin esto el archivo no entra al corte.",
                   en:"Barrett pays once the loan funded, the check arrived and these documents are in Arive. Without them the file does not enter the cut." },
  checkReceived:{ es:"Cheque recibido por Barrett", en:"Broker check received" },
  checkWhere: { es:"En Arive lo ves en Audits & Dates → Broker Check Received",
                en:"In Arive, see Audits & Dates → Broker Check Received" },
  docsOf:     { es:"{a} de {b} documentos", en:"{a} of {b} documents" },
  blocked:    { es:"NO COBRABLE", en:"BLOCKED" },
  blockedN:   { es:"{n} fondeado(s) sin poder cobrar", en:"{n} funded but not payable" },
  blockedWhy: { es:"le falta:", en:"missing:" },
  paysOn:     { es:"se paga {d}", en:"paid {d}" },
  extraPayroll:{ es:"Barrett procesa un Extra Payroll fuera de ciclo. La solicitud entra antes de la 1PM del jueves y el depósito cae el martes siguiente.",
                 en:"Barrett runs an off-cycle Extra Payroll. The request goes in before 1PM Thursday and the deposit lands the following Tuesday." },

  newVersion:{ es:"Hay una versión nueva del pipeline. La que tienes abierta puede mostrar datos o reglas viejas.",
               en:"There is a newer version of the pipeline. The one you have open may show old data or old rules." },
  newVersionBtn:{ es:"RECARGAR", en:"RELOAD" },

  noCoeYet:{ es:"Sin contrato no hay fecha de cierre. Se llena cuando el archivo llegue a Under Contract.",
             en:"No contract, no closing date. It fills in when the file reaches Under Contract." },

  notInList:{ es:"no está en la lista", en:"not in the list" },
  notInListHint:{ es:"Este valor no es de la lista. Escoge el correcto — mientras siga así, el archivo no cuenta en producción.",
                  en:"This value is not from the list. Pick the right one — until then, the file does not count in production." },

  // ─── checklist de sometimiento ───
  subTab:{ es:"DOCUMENTOS", en:"DOCUMENTS" },
  subComplete:{ es:"documentos en el expediente · completo",
                en:"documents in the file · complete" },
  subMissing:{ es:"documentos en el expediente · faltan {n}",
               en:"documents in the file · {n} missing" },
  subDerived:{ es:"La lista sale sola de: {p} · {i} · y las condiciones del contrato",
               en:"The list is derived from: {p} · {i} · and the contract conditions" },
  subConditions:{ es:"CONDICIONES DE ESTE ARCHIVO", en:"CONDITIONS ON THIS FILE" },
  subLetters:{ es:"CARTAS QUE HAY QUE ANTICIPAR", en:"LETTERS TO PREPARE AHEAD" },
  subLettersHint:{ es:"El sistema las nombra antes de que underwriting las pida. Prepararlas ahora ahorra días después.",
                   en:"The system names them before underwriting asks. Preparing them now saves days later." },
  subThresholds:{ es:"UMBRALES DE ESTE ARCHIVO", en:"THRESHOLDS ON THIS FILE" },
  subEmd:{ es:"Depósito de buena fe · 1% del precio (FHA)",
           en:"Earnest money · 1% of sales price (FHA)" },
  subEmdNa:{ es:"el 1% es regla de FHA", en:"the 1% is an FHA rule" },
  subLargeDep:{ es:"Depósito grande · 50% del ingreso mensual",
                en:"Large deposit · 50% of monthly income" },
  subRefiNa:{ es:"no se exige en refinanciamiento", en:"not required on a refinance" },
  subNoIncome:{ es:"falta capturar el ingreso", en:"income not captured yet" },
  subNotApplicable:{ es:"{n} no aplican a este archivo", en:"{n} do not apply to this file" },

  riskTitle:{ es:"BANDERAS DE RIESGO", en:"RISK FLAGS" },
  riskHint:{ es:"Marca lo que ves al mirar el archivo. El sistema saca las condiciones que underwriting va a pedir por eso — antes de que las pida.",
             en:"Mark what you see when you look at the file. The system produces the conditions underwriting will ask for — before they ask." },
  riskAuto:{ es:"la calcula el sistema", en:"calculated by the system" },
  riskDocs:{ es:"{n} CONDICIONES QUE PIDEN LAS BANDERAS",
             en:"{n} CONDITIONS THE FLAGS CALL FOR" },
  laterTitle:{ es:"DESPUÉS DE LA APROBACIÓN", en:"AFTER APPROVAL" },
  timing_pta:{ es:"cuenta para registrar", en:"counts toward registering" },
  timing_ptc:{ es:"la tasación y el título todavía no existen — no bloquea",
               en:"the appraisal and title do not exist yet — does not block" },
  timing_ptf:{ es:"lo último, justo antes de que el dinero salga",
               en:"the last step, right before the money moves" },
  laterHint:{ es:"No cuentan para registrar: la tasación y el título todavía no existen. Se ven aquí para ir pidiéndolos.",
              en:"These do not count toward registering: the appraisal and title do not exist yet. They are here so you can start asking." },
  customTitle:{ es:"ESCRITOS A MANO", en:"WRITTEN IN" },
  customPlaceholder:{ es:"Otra condición que pidió el underwriter…",
                      en:"Another condition the underwriter asked for…" },
  customAdd:{ es:"AÑADIR", en:"ADD" },

  // ─── la puerta antes de registrar ───
  subGate:{ es:"DOCUMENTOS ANTES DE REGISTRAR", en:"DOCUMENTS BEFORE REGISTERING" },
  subGateOk:{ es:"Todo en el expediente — listo para registrar",
              en:"Everything in the file — ready to register" },
  subGateShort:{ es:"Faltan {n} de {t}", en:"{n} of {t} missing" },
  subGateHint:{ es:"Se puede registrar igual. Queda constancia de quién decidió seguir.",
                en:"You can register anyway. It records who decided to proceed." },
  subGateWhere:{ es:"El detalle está en la solapa DOCUMENTOS.",
                 en:"The detail is on the DOCUMENTS tab." },

  // ─── historial de empleo y residencia ───
  years:{ es:"AÑOS", en:"YEARS" },
  histCovered:{ es:"{n} meses cubiertos ✓", en:"{n} months covered ✓" },
  histShort:{ es:"{n} de {t} meses", en:"{n} of {t} months" },
  histFrom:{ es:"DESDE", en:"FROM" },
  histTo:{ es:"HASTA", en:"TO" },
  histToOrCurrent:{ es:"HASTA · vacío = actual", en:"TO · blank = current" },
  histCurrent:{ es:"actual", en:"current" },
  histOpenError:{ es:"⚑ {n} renglón(es) sin fecha de salida y hay uno más reciente — nadie está en dos a la vez",
                  en:"⚑ {n} row(s) with no end date while a newer one exists — nobody is in two at once" },
  histAdd:{ es:"+ otro renglón", en:"+ another row" },
  histAddShort:{ es:"+ renglón anterior · faltan {n} meses",
                 en:"+ earlier row · {n} months missing" },
  histGap:{ es:"⚑ Hueco de {n} meses — pide carta de explicación",
            en:"⚑ {n}-month gap — needs a letter of explanation" },
  histEmpHint:{ es:"Un hueco de 6 meses o más pide carta. El sistema los detecta solo.",
                en:"A gap of 6 months or more needs a letter. The system finds them on its own." },
  histResHint:{ es:"Las direcciones del reporte de crédito que no aparezcan aquí piden carta.",
                en:"Addresses on the credit report that are not listed here need a letter." },

  // ─── contrato cancelado ───
  cancelBtn:{ es:"⤺ CONTRATO CANCELADO", en:"⤺ CONTRACT CANCELLED" },
  cancelTitle:{ es:"El contrato se cayó", en:"The contract fell through" },
  cancelLead:{ es:"El cliente NO se pierde: sigue vivo, sigue siendo tuyo y sigue contando para tu socio referidor. Lo que se cae es el contrato de esta casa.",
               en:"The client is NOT lost: still alive, still yours, still counting for your referral partner. What falls through is the contract on this house." },
  cancelWhat:{ es:"Se borran las contingencias, el COE, el lender, el lock, el registro y los pedidos — eran de esta propiedad. La verificación del 1003, las notas y la admisión se quedan: son del cliente.",
               en:"Contingencies, COE, lender, lock, registration and orders are cleared — they belonged to this property. The 1003 verification, the notes and the intake stay: they belong to the client." },
  cancelWhere:{ es:"Vuelve a Active Search con el reloj de búsqueda en cero.",
                en:"Goes back to Active Search with the house-hunt clock reset." },
  cancelWhy:{ es:"POR QUÉ SE CAYÓ", en:"WHY IT FELL THROUGH" },
  cancelNote:{ es:"Qué pasó · quién lo confirmó", en:"What happened · who confirmed it" },
  cancelDo:{ es:"CANCELAR EL CONTRATO", en:"CANCEL THE CONTRACT" },
  cancelNth:{ es:"contrato caído {n} de este cliente", en:"contract {n} to fall through for this client" },
  cancelWas:{ es:"Contrato caído el {d} · {r}", en:"Contract fell through {d} · {r}" },

  // ─── tareas vencidas ───
  overdueLine:{ es:"{n} tareas vencidas", en:"{n} overdue tasks" },
  overdueOne:{ es:"1 tarea vencida", en:"1 overdue task" },
  overdueNone:{ es:"Nada vencido en esta cola.", en:"Nothing overdue in this queue." },
  overdueAsOf:{ es:"al {d}", en:"as of {d}" },
  overdueShow:{ es:"VER", en:"SHOW" },
  overdueAll:{ es:"VER TODO", en:"SHOW ALL" },
  overdueTab:{ es:"⏱ TAREAS VENCIDAS", en:"⏱ OVERDUE TASKS" },
  overdueLead:{ es:"Lo que ya pasó su plazo, ordenado por lo que cuesta. El depósito del cliente pesa más que un techo de etapa, y un plazo de ley no negocia.",
                en:"What has passed its deadline, ordered by what it costs. The client's deposit outweighs a stage ceiling, and a legal deadline does not negotiate." },
  overdueClean:{ es:"✓ Nada vencido en todo el pipeline.", en:"✓ Nothing overdue across the pipeline." },
  overdueFiles:{ es:"archivos necesitan movimiento hoy", en:"files need movement today" },
  overdueOpenHint:{ es:"Toca cualquier renglón para abrir el archivo. Un archivo cuenta una vez, con lo peor que tenga — el +N dice cuántas más le deben.",
                    en:"Tap any row to open the file. A file counts once, with its worst item — the +N says how many more it owes." },

  // ─── el estándar de tres días ───
  leadStd:{ es:"ESTÁNDAR DE {n} DÍAS", en:"{n}-DAY STANDARD" },
  leadClock:{ es:"{n}d hábiles en Pre-Qual", en:"{n} business days in Pre-Qual" },
  leadDueBy:{ es:"se decide el {d}", en:"decide by {d}" },
  leadOver:{ es:"{n}d sobre el estándar", en:"{n}d over the standard" },
  leadExits:{ es:"precalifica, prepara o archiva — quedarse no es una salida",
              en:"pre-qualify, prepare or archive — staying is not an exit" },
  leadMet:{ es:"dentro del estándar", en:"within the standard" },
  leadReportTitle:{ es:"⏱ ESTÁNDAR DE RESPUESTA", en:"⏱ RESPONSE STANDARD" },
  leadReportLead:{ es:"Lo que la sucursal le promete a un agente: un lead que entra se decide en {n} días hábiles. Decidido es precalificado, mandado a preparación o archivado — lo que cuenta es que alguien decidió.",
                   en:"What the branch promises an agent: a lead that comes in gets decided within {n} business days. Decided means pre-qualified, sent to preparation or archived — what counts is that somebody decided." },
  leadPct:{ es:"{p}% dentro del estándar", en:"{p}% within the standard" },
  leadCounts:{ es:"{m} cumplidos · {b} rotos · {o} todavía abiertos",
               en:"{m} met · {b} broken · {o} still open" },
  leadAvg:{ es:"promedio {n} días hábiles", en:"average {n} business days" },
  leadNoData:{ es:"Todavía no hay leads con fecha de entrada sellada.",
               en:"No leads with a stamped entry date yet." },
  leadGatePrequal:{ es:"precalificado", en:"pre-qualified" },
  leadGatePrep:{ es:"a preparación", en:"to preparation" },
  leadGateArch:{ es:"archivado", en:"archived" },
  leadGateOpen:{ es:"todavía abierto", en:"still open" },

  // ─── tiempo ───
  inStage:     { es:"d en la etapa", en:"d in stage" },
  total:       { es:"d total",       en:"d total" },
  closeIn:     { es:"Cierra en",     en:"Close in" },
  ago:         { es:"hace",          en:"ago" },
  justNow:     { es:"ahora mismo",   en:"just now" },
};

// Traduce una clave. Si falta la traducción, devuelve el español antes que
// una clave cruda: un texto en el idioma equivocado se entiende; "loanType"
// no se entiende en ninguno.
export function tr(key, lang = "es", vars) {
  const e = UI[key];
  let out = e ? (e[lang] ?? e.es ?? e.en ?? key) : key;
  if (vars) for (const [k, v] of Object.entries(vars)) out = out.split("{" + k + "}").join(v);
  return out;
}

// Idioma por defecto según el rol. El equipo trabaja en español; quien
// administra puede cambiarlo y queda guardado en su perfil.
// El idioma sale del roster, no de un default unico. Martha no lee
// espanol: si aterriza en una pantalla en espanol tiene que buscar un
// boton que no sabe leer para poder cambiarla. Cada quien entra en el
// suyo desde el primer login.
export const defaultLang = profile => (profile?.lang === "en" ? "en" : "es");
